openapi: 3.0.3
info:
  title: Childhood Cancer Catalog of Circular Extrachromosomal DNA API
  version: 1.0.0
  description: Documentation for the Childhood Cancer Catalog of Circular Extrachromosomal
    DNA API
paths:
  /api/amplicons/:
    get:
      operationId: amplicons_list
      description: Retrieve the list of amplicons with optional filtering parameters
      parameters:
      - in: query
        name: amplicon_number
        schema:
          type: string
        description: Filter by Amplicon Number (Optional)
      - in: query
        name: biosample_id
        schema:
          type: string
        description: Filter by Biosample ID (Optional)
      - in: query
        name: patient_id
        schema:
          type: string
        description: Filter by Patient ID (Optional)
      tags:
      - amplicons
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Amplicon'
          description: ''
  /api/amplicons/download-plot/:
    get:
      operationId: download_amplicon_plot
      description: Download the plot for a specific amplicon cycle as an HTML file.
      parameters:
      - in: query
        name: amplicon_no
        schema:
          type: string
        description: Amplicon number
        required: true
      - in: query
        name: biosample_id
        schema:
          type: string
        description: ID of the biosample
        required: true
      - in: query
        name: cycle_no
        schema:
          type: string
        description: Cycle number
        required: true
      tags:
      - amplicons
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
                description: Unspecified response body
          description: HTML file containing plot data
        '400':
          description: Bad request, missing required parameters
        '404':
          description: Biosample, Amplicon, or Plot not found
  /api/amplified-genes/:
    get:
      operationId: amplified_genes_list
      tags:
      - amplified-genes
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AmplifiedGenes'
          description: ''
  /api/amplified-genes/{id}/:
    get:
      operationId: amplified_genes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this amplified gene.
        required: true
      tags:
      - amplified-genes
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmplifiedGenes'
          description: ''
  /api/biosamples/:
    get:
      operationId: biosamples_list
      description: Retrieve the list of biosamples entries
      tags:
      - biosamples
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Biosamples'
          description: ''
  /api/biosamples/{biosample_id}/:
    get:
      operationId: biosamples_retrieve
      description: Retrieve a biosamples entry using a unique sample ID
      parameters:
      - in: path
        name: biosample_id
        schema:
          type: string
        description: A unique value identifying this biosample.
        required: true
      tags:
      - biosamples
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Biosamples'
          description: ''
  /api/biosamples/{biosample_id}/aatgz/:
    get:
      operationId: get_biosample_aatgz
      description: Retrieve the Amplicon Architect output (in .tar.gz) for a given
        biosample ID.
      summary: Download the Amplicon Architect output (.tar.gz) for the biosample
      parameters:
      - in: path
        name: biosample_id
        schema:
          type: string
        description: A unique value identifying this biosample.
        required: true
      tags:
      - biosamples
      responses:
        '200':
          content:
            application/json:
              schema:
                content:
                  application/gzip:
                    schema:
                      type: string
                      format: binary
                    example: Binary content of the .tar.gz file
                description: A TGZ file will be downloaded.
          description: ''
        '400':
          content:
            application/json:
              schema:
                description: Biosample AA TGZ file not found for the given ID
          description: ''
  /api/biosamples/{biosample_id}/aazip/:
    get:
      operationId: get_biosample_aazip
      description: Retrieve the Amplicon Architect output (in .zip) for a given biosample
        ID.
      summary: Download the Amplicon Architect output (.zip) for the biosample
      parameters:
      - in: path
        name: biosample_id
        schema:
          type: string
        description: A unique value identifying this biosample.
        required: true
      tags:
      - biosamples
      responses:
        '200':
          content:
            application/json:
              schema:
                content:
                  application/zip:
                    schema:
                      type: string
                      format: binary
                    example: Binary content of the .zip file
                description: A ZIP file will be downloaded.
          description: ''
        '400':
          content:
            application/json:
              schema:
                description: Biosample AA ZIP file not found for the given ID
          description: ''
  /api/gene-annotate-patient/:
    post:
      operationId: gene_annotate_patient_create
      description: Retrieve patients list annotated with the gene ampliciation status
        based on the provided gene name.
      tags:
      - gene-annotate-patient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneName'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GeneName'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/GeneName'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientWithGeneAnnotation'
          description: ''
  /api/patients/:
    get:
      operationId: patients_list
      description: Retrieve the list of patient entries
      tags:
      - patients
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
          description: ''
  /api/patients/{patient_id}/:
    get:
      operationId: patients_retrieve
      description: Retrieve a patient entry using a unique patient ID
      parameters:
      - in: path
        name: patient_id
        schema:
          type: string
        description: A unique value identifying this patient.
        required: true
      tags:
      - patients
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
components:
  schemas:
    Amplicon:
      type: object
      properties:
        amplicon_number:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        amplicon_decomposition_class:
          type: string
          maxLength: 100
        ecDNA_positive:
          type: boolean
        BFB_positive:
          type: boolean
        ecDNA_amplicons:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        biosample_id:
          type: string
          readOnly: true
        patient_id:
          type: string
          readOnly: true
        json_plot_available:
          type: boolean
          readOnly: true
        amplicon_repository_url:
          type: string
          format: uri
          readOnly: true
        amplicon_repository_available:
          type: boolean
          readOnly: true
        available_cycles:
          type: array
          items:
            type: integer
        copy_counts:
          type: array
          items:
            type: number
            format: double
      required:
      - BFB_positive
      - amplicon_decomposition_class
      - amplicon_number
      - amplicon_repository_available
      - amplicon_repository_url
      - available_cycles
      - biosample_id
      - copy_counts
      - ecDNA_amplicons
      - ecDNA_positive
      - json_plot_available
      - patient_id
    AmplifiedGenes:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        gene_name:
          type: string
          maxLength: 100
        mean_gene_cn:
          type: number
          format: double
          nullable: true
        median_gene_cn:
          type: number
          format: double
          nullable: true
        lower_quartile_gene_cn:
          type: number
          format: double
          nullable: true
        upper_quartile_gene_cn:
          type: number
          format: double
          nullable: true
        amplicons_count:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        biosamples_count:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        patients_count:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        is_canonical_oncogene_consensus:
          type: boolean
          nullable: true
      required:
      - gene_name
      - id
    Biosamples:
      type: object
      properties:
        biosample_id:
          type: string
          maxLength: 100
        patient_id:
          type: string
          readOnly: true
        external_sample_id:
          type: string
          nullable: true
          maxLength: 100
        tumor_history:
          type: string
          nullable: true
          maxLength: 100
        age_at_diagnosis:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        extent_of_tumor_resection:
          type: string
          nullable: true
          maxLength: 100
        cancer_type:
          type: string
          maxLength: 100
        cancer_subclass:
          type: string
          nullable: true
          maxLength: 100
        ecDNA_sequences_detected:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        amplicon_class:
          type: string
          maxLength: 100
        in_unique_tumor_set:
          type: boolean
          nullable: true
        in_unique_patient_set:
          type: boolean
          nullable: true
        amplicon_repository_url:
          type: string
          format: uri
          nullable: true
          maxLength: 512
        amplicon_repository_available:
          type: array
          items:
            type: integer
          nullable: true
          readOnly: true
        no_of_amplicons:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        aafile_available:
          type: boolean
      required:
      - amplicon_class
      - amplicon_repository_available
      - biosample_id
      - cancer_type
      - ecDNA_sequences_detected
      - patient_id
    Cohort:
      type: object
      properties:
        name:
          type: string
          maxLength: 20
      required:
      - name
    GeneName:
      type: object
      properties:
        gene_name:
          type: string
      required:
      - gene_name
    OSStatusEnum:
      enum:
      - A
      - D
      - U
      type: string
      description: |-
        * `A` - Alive
        * `D` - Deceased
        * `U` - Unknown
    Patient:
      type: object
      properties:
        patient_id:
          type: string
          maxLength: 100
        cohorts:
          type: array
          items:
            $ref: '#/components/schemas/Cohort'
          readOnly: true
        sex:
          $ref: '#/components/schemas/SexEnum'
        age_at_diagnosis:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        cancer_type:
          type: string
          maxLength: 100
        cancer_subclass:
          type: string
          maxLength: 100
        amplicon_class:
          type: string
          maxLength: 100
        OS_status:
          $ref: '#/components/schemas/OSStatusEnum'
        OS_months:
          type: number
          format: double
          nullable: true
        no_of_biosamples:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
      required:
      - OS_status
      - amplicon_class
      - cancer_subclass
      - cancer_type
      - cohorts
      - patient_id
      - sex
    PatientWithGeneAnnotation:
      type: object
      properties:
        patient_id:
          type: string
          maxLength: 100
        sex:
          $ref: '#/components/schemas/SexEnum'
        cohorts:
          type: array
          items:
            $ref: '#/components/schemas/Cohort'
          readOnly: true
        age_at_diagnosis:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        cancer_type:
          type: string
          maxLength: 100
        cancer_subclass:
          type: string
          maxLength: 100
        amplicon_class:
          type: string
          maxLength: 100
        OS_status:
          $ref: '#/components/schemas/OSStatusEnum'
        OS_months:
          type: number
          format: double
          nullable: true
        has_gene_harboring_amplicon:
          type: boolean
        gene_harboring_amplicon_class:
          type: string
        gene_harboring_amplicon_classes_counts:
          type: string
        gene_copy_number:
          type: number
          format: double
        no_of_biosamples:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
      required:
      - OS_status
      - amplicon_class
      - cancer_subclass
      - cancer_type
      - cohorts
      - gene_copy_number
      - gene_harboring_amplicon_class
      - gene_harboring_amplicon_classes_counts
      - has_gene_harboring_amplicon
      - patient_id
      - sex
    SexEnum:
      enum:
      - M
      - F
      - U
      type: string
      description: |-
        * `M` - Male
        * `F` - Female
        * `U` - Unknown
tags:
- name: patients
  description: Patient within the catalog.
- name: biosamples
  description: Biosamples within the catalog
- name: amplicons
  description: Amplicons within the catalog
- name: amplified-genes
  description: Genes amplified on amplicons within the catalog
